Vagrant.configure("2") do |config|

	config.vm.box = "generic/alpine318"


	config.vm.define "jubernarS" do |control|
		control.vm.hostname = "jubernarS"
		control.vm.network "private_network", ip: "192.168.56.110"
		control.vm.provider "virtualbox" do |vb|
			vb.memory = 1024
			vb.cpus = 1
		end
		control.vm.provision "shell", inline: <<-SHELL
			curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --cluster-init --token iot
		SHELL
	end

	config.vm.define "jubernarSW" do |control|
		control.vm.hostname = "jubernarSW"
		control.vm.network "private_network", ip: "192.168.56.111"
		control.vm.provider "virtualbox" do |vb|
			vb.memory = 1024
			vb.cpus = 1
		end
		control.vm.provision "shell", inline: <<-SHELL
			curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 sh -s - agent --token iot
		SHELL
	end

end
