Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__auto: true

  config.vm.define "ashojachS" do |control|
    control.vm.box = "generic/alpine318"
    control.vm.hostname = "ashojachS"
    control.vm.network "private_network", ip: "192.168.56.110"

    control.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    control.vm.provision "shell", inline: <<-SHELL
      #!/bin/sh

      until ip a show eth1 | grep "192.168.56.110"; do sleep 2; done

      export INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --node-ip 192.168.56.110"
      bash <(curl -sfL https://get.k3s.io)

      sleep 5

      until [ -d /vagrant ]; do sleep 2; done

      sudo cat /var/lib/rancher/k3s/server/token > /vagrant/token.env

    SHELL
  end

  config.vm.define "ashojachSW" do |control|
    control.vm.box = "generic/alpine318"
    control.vm.hostname = "ashojachSW"
    control.vm.network "private_network", ip: "192.168.56.111"

    control.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    control.vm.provision "shell", inline: <<-SHELL
      #!/bin/sh

      until ip a show eth1 | grep "192.168.56.111"; do sleep 2; done

      until [ -d /vagrant ]; do sleep 2; done

      while [ ! -s /vagrant/token.env ]; do sleep 5; done

      export INSTALL_K3S_EXEC="agent --server https://192.168.56.110:6443 --token=$(cat /vagrant/token.env) --node-ip=192.168.56.111"
      bash <(curl -sfL https://get.k3s.io)

    SHELL
  end
end

