Vagrant.configure("2") do |config|

	config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__auto: true

	config.vm.define "jubernarS" do |control|
		config.vm.box = "bento/debian-12.9"
		control.vm.hostname = "jubernarS"
		control.vm.network "private_network", ip: "192.168.56.110"
		control.vm.provider "virtualbox" do |vb|
			vb.memory = 2024
			vb.cpus = 2
		end
		control.vm.provision "shell", inline: <<-SHELL
			curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --cluster-init --token iot

			echo "Waiting for Kubernetes API to be ready..."
			until kubectl get nodes &>/dev/null; do
				echo "Kubernetes not ready yet, sleeping..."
				sleep 3
			done
			echo "Kubernetes is ready!"

			kubectl apply -f /vagrant/confs/app1.yaml
			kubectl apply -f /vagrant/confs/app2.yaml
			kubectl apply -f /vagrant/confs/app3.yaml
			kubectl apply -f /vagrant/confs/ingress.yaml
		SHELL
	end
end


