Vagrant.configure("2") do |config|

	config.vm.box = "bento/debian-12.9"

	config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__auto: true

	config.vm.define "jubernarS" do |control|
		control.vm.hostname = "jubernarS"
		control.vm.network "private_network", ip: "192.168.56.110"
		control.vm.provider "virtualbox" do |vb|
			vb.memory = 2048
			vb.cpus = 2
		end
		control.vm.provision "shell", inline: <<-SHELL
			curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --cluster-init --token iot
			kubectl apply -f /vagrant/confs/app1.yaml
			kubectl apply -f /vagrant/confs/app2.yaml
			kubectl apply -f /vagrant/confs/app3.yaml
			kubectl apply -f /vagrant/confs/ingress.yaml
		SHELL
	end

end
